-- =====================================================================
--  Liên đoàn Hướng đạo Long Biên — lược đồ cơ sở dữ liệu
--  Dán toàn bộ file này vào Supabase → SQL Editor → Run. Chạy lại được
--  nhiều lần mà không lỗi.
-- =====================================================================

-- ---------------------------------------------------------------------
-- 1. Bảng ghi nhận lượt xem
--    Cố tình KHÔNG lưu địa chỉ IP và KHÔNG đặt cookie theo dõi.
--    session_id là mã ngẫu nhiên do trình duyệt sinh ra, mất khi đóng tab.
-- ---------------------------------------------------------------------
create table if not exists public.page_views (
  id            bigint generated by default as identity primary key,
  created_at    timestamptz  not null default now(),
  path          text         not null default '/',
  referrer_host text         not null default '',   -- chỉ tên miền, không lưu URL đầy đủ
  utm_source    text         not null default '',
  utm_medium    text         not null default '',
  utm_campaign  text         not null default '',
  tz            text         not null default '',   -- múi giờ máy khách, dùng để ước lượng khu vực
  lang          text         not null default '',
  device        text         not null default '',   -- mobile | tablet | desktop
  screen_w      int,
  session_id    text         not null default ''
);

create index if not exists page_views_created_idx on public.page_views (created_at desc);
create index if not exists page_views_session_idx on public.page_views (session_id);

alter table public.page_views enable row level security;

-- Khách ẩn danh CHỈ được ghi thêm, không được đọc lại số liệu của người khác.
drop policy if exists "khach_ghi_luot_xem" on public.page_views;
create policy "khach_ghi_luot_xem" on public.page_views
  for insert to anon with check (true);

-- Chỉ tài khoản đã đăng nhập mới đọc được số liệu.
drop policy if exists "quan_tri_doc_luot_xem" on public.page_views;
create policy "quan_tri_doc_luot_xem" on public.page_views
  for select to authenticated using (true);

-- Chặn ghi rác: không cho một phiên nhồi quá 200 dòng mỗi giờ.
create or replace function public.chan_ghi_rac() returns trigger
language plpgsql security definer set search_path = public as $$
declare n int;
begin
  select count(*) into n from public.page_views
   where session_id = new.session_id and created_at > now() - interval '1 hour';
  if n > 200 then
    return null;   -- lặng lẽ bỏ qua, không báo lỗi ra trang web
  end if;
  -- cắt bớt để không ai nhồi chuỗi dài vào bảng
  new.path          := left(coalesce(new.path,''),300);
  new.referrer_host := left(coalesce(new.referrer_host,''),120);
  new.utm_source    := left(coalesce(new.utm_source,''),60);
  new.utm_medium    := left(coalesce(new.utm_medium,''),60);
  new.utm_campaign  := left(coalesce(new.utm_campaign,''),80);
  new.tz            := left(coalesce(new.tz,''),60);
  new.lang          := left(coalesce(new.lang,''),12);
  new.device        := left(coalesce(new.device,''),12);
  new.session_id    := left(coalesce(new.session_id,''),64);
  return new;
end $$;

drop trigger if exists trg_chan_ghi_rac on public.page_views;
create trigger trg_chan_ghi_rac before insert on public.page_views
  for each row execute function public.chan_ghi_rac();

-- ---------------------------------------------------------------------
-- 2. Nội dung website (danh sách album ảnh)
--    Ai cũng đọc được (trang công khai cần đọc), chỉ người đăng nhập được sửa.
-- ---------------------------------------------------------------------
create table if not exists public.site_content (
  key        text primary key,
  data       jsonb       not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

alter table public.site_content enable row level security;

drop policy if exists "ai_cung_doc_noi_dung" on public.site_content;
create policy "ai_cung_doc_noi_dung" on public.site_content
  for select to anon, authenticated using (true);

drop policy if exists "quan_tri_ghi_noi_dung" on public.site_content;
create policy "quan_tri_ghi_noi_dung" on public.site_content
  for all to authenticated using (true) with check (true);

-- ---------------------------------------------------------------------
-- 3. Kho ảnh (Storage)
--    Tạo bucket 'gallery' công khai; chỉ người đăng nhập được tải ảnh lên.
-- ---------------------------------------------------------------------
insert into storage.buckets (id, name, public)
values ('gallery','gallery',true)
on conflict (id) do update set public = true;

drop policy if exists "ai_cung_xem_anh" on storage.objects;
create policy "ai_cung_xem_anh" on storage.objects
  for select to anon, authenticated using (bucket_id = 'gallery');

drop policy if exists "quan_tri_tai_anh_len" on storage.objects;
create policy "quan_tri_tai_anh_len" on storage.objects
  for insert to authenticated with check (bucket_id = 'gallery');

drop policy if exists "quan_tri_ghi_de_anh" on storage.objects;
create policy "quan_tri_ghi_de_anh" on storage.objects
  for update to authenticated using (bucket_id = 'gallery');

drop policy if exists "quan_tri_xoa_anh" on storage.objects;
create policy "quan_tri_xoa_anh" on storage.objects
  for delete to authenticated using (bucket_id = 'gallery');

-- ---------------------------------------------------------------------
-- 4. Dọn dẹp định kỳ (tuỳ chọn)
--    Chỉ giữ số liệu 400 ngày gần nhất. Gọi tay, hoặc hẹn giờ bằng pg_cron.
-- ---------------------------------------------------------------------
create or replace function public.don_so_lieu_cu() returns void
language sql security definer set search_path = public as $$
  delete from public.page_views where created_at < now() - interval '400 days';
$$;

-- =====================================================================
--  Sau khi chạy xong:
--   • Authentication → Users → thêm tài khoản email/mật khẩu cho Ban Huynh trưởng
--   • Settings → API → copy Project URL và khoá anon public
--   • Dán 2 giá trị đó vào CONFIG trong index.html và biến SB trong admin.html
-- =====================================================================
